# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI

on:
  push:
    tags:
      - '*'
    branches: [ main,dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Build with Gradle
        uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
        with:
          arguments: Mod_Repo:uberJar

      - name: Set Variables
        run: |
          git log --format=%B -n 1 $(git log -1 --pretty=format:"%h") | cat - > changes.txt

      - name: Publish Release on GitHub
        uses: "ncipollo/release-action@v1"
        with:
          bodyFile: changes.txt
          draft: false
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "Mod_Repo/dist/*"