# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build SMOL for Windows and Create Release from Tag

on:
  push:
    tags:
      - "smol-*"

jobs:
  build_and_publish:
    runs-on: windows-latest

    steps:
      # Check version in tag
      - uses: nowsprinting/check-version-format-action@v3
        id: version
        with:
          prefix: "smol-"

      - name: Print version info if valid
        run: |
          echo "Found valid version format in tag!"
          echo "Full version: ${{ steps.version.outputs.full }}"
          echo "Major version: ${{ steps.version.outputs.major }}"
          echo "Major with pre-release: ${{ steps.version.outputs.major_prerelease }}"
          echo "Is stable: ${{ steps.version.outputs.is_stable }}"
        if: steps.version.outputs.is_valid == 'true'

      - name: Print version warning if invalid
        run: |
          echo "Found invalid version format in tag!"
        if: steps.version.outputs.is_valid == 'false'

      # git checkout
      - uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.

      # Install dependency: JDK
      - name: Set up JDK 16
        if: steps.version.outputs.is_valid == 'true'
        uses: actions/setup-java@v2
        with:
          java-version: "16"
          distribution: "adopt"

      # Build
      - name: Validate Gradle wrapper
        if: steps.version.outputs.is_valid == 'true'
        uses: gradle/wrapper-validation-action@v1

      - name: Build Unstable
        if: steps.version.outputs.is_valid == 'true' && contains(steps.version.outputs.full, 'unstable')
        uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
        with:
          arguments: buildSmolDistUnstable

      - name: Build Test
        if: steps.version.outputs.is_valid == 'true' && contains(steps.version.outputs.full, 'test')
        uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
        with:
          arguments: buildSmolDistTest

      # Publish
      - name: Commit files
        run: |
          git config --local user.email "1343347+davidwhitman@users.noreply.github.com"
          git config --local user.name "Beta Core [GitHub Actions]"
          git add .
          git commit -m "{{ steps.version.outputs.full }}"

      - name: Publish Test to SMOL_Dist
        if: steps.version.outputs.is_valid == 'true' && contains(steps.version.outputs.full, 'test')
        uses: ad-m/github-push-action@master
        with:
          repository: "davidwhitman/SMOL_Dist"
          branch: "test"
          directory: "dist/main/app/SMOL/"
          github_token: ${{ secrets.WRITE_PAT }}
